#!/usr/bin/env python3

# add directory 'src' to sys.path
import os
import sys

current_dir = os.path.dirname(os.path.realpath(__file__))
project_root = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.append(project_root)

import argparse  # noqa

parser = argparse.ArgumentParser(description="Create playlist from Spotify to YouTube.")
parser.add_argument(
    "--id", required=True, help="The id of the playlist", metavar="spotify_id"
)


def main(spotify_id: str) -> None:
    from src.database.connection import Database, STdb
    from src.main import CLIENT_ID, CLIENT_SECRET, YT_CREDENTIAL_FILE_NAME
    from src.spot_tube import SpotTube

    st = SpotTube(CLIENT_ID, CLIENT_SECRET, YT_CREDENTIAL_FILE_NAME, STdb(Database()))
    st.do_transfer(spotify_id)


if __name__ == "__main__":
    args = parser.parse_args()
    spotify_id = args.id
    main(spotify_id)
